// sso-kit-react-demo/frontend/views/MainLayout.tsx
import { logout as _logout } from '@hilla/frontend';
import { AppLayout } from '@hilla/react-components/AppLayout.js';
import { Button } from '@hilla/react-components/Button.js';
import { ConfirmDialog } from '@hilla/react-components/ConfirmDialog.js';
import { DrawerToggle } from '@hilla/react-components/DrawerToggle.js';
import { Item } from '@hilla/react-components/Item.js';
import { Scroller } from '@hilla/react-components/Scroller.js';
import Placeholder from 'Frontend/components/placeholder/Placeholder.js';
import { MenuProps, routes, useViewMatches, ViewRouteObject } from 'Frontend/routes.js';
import { AuthContext } from 'Frontend/useAuth.js';
import { Suspense, useContext, useEffect } from 'react';
import { NavLink, Outlet } from 'react-router-dom';
import css from './MainLayout.module.css';

type MenuRoute = ViewRouteObject &
  Readonly<{
    path: string;
    handle: Required<MenuProps>;
  }>;

export default function MenuOnLeftLayout() {
  const { state, hasAccess, onBackChannelLogout, clearUserInfo } = useContext(AuthContext);
  const matches = useViewMatches();

  useEffect(() => {
    if (state.backChannelLogout) {
      state.backChannelLogout.onNext(() => {
        onBackChannelLogout();
      });
    }
  }, []);

  const currentTitle = matches[matches.length - 1]?.handle?.title ?? 'Unknown';

  const menuRoutes = (routes[0]?.children || []).filter(
    (route) => route.path && route.handle && route.handle.icon && route.handle.title
  ) as readonly MenuRoute[];

  async function logout() {
    await _logout();
    location.href = state.logoutUrl!;
  }

  async function loginAgain() { 
    await _logout();
    location.href = '/oauth2/authorization/' + state.registeredProviders[0];
  }

  async function stayOnPage() { 
    await _logout();
    clearUserInfo();
  }

  return (
    <AppLayout className="block h-full" primarySection="drawer">
      <header slot="drawer">
        <h1 className="text-l m-0">My App</h1>
      </header>
      <Scroller slot="drawer" scroll-direction="vertical">
        <nav>
          {menuRoutes.filter(hasAccess).map(({ path, handle: { icon, title } }) => (
            <NavLink
              className={({ isActive }) => `${css.navlink} ${isActive ? css.navlink_active : ''}`}
              key={path}
              to={path}
            >
              {({ isActive }) => (
                <Item key={path} selected={isActive}>
                  <span className={`${icon} ${css.navicon}`} aria-hidden="true"></span>
                  {title}
                </Item>
              )}
            </NavLink>
          ))}
        </nav>
      </Scroller>
      <footer slot="drawer">
        {state.user ? (
          <>
            <div className="flex items-center gap-m">
              {state.user.fullName}
            </div>
            <Button onClick={logout}>Sign out</Button>
          </>
        ) : (
          <a href={'/oauth2/authorization/' + state.registeredProviders[0]}>Sign in</a>
        )}
      </footer>

      <DrawerToggle slot="navbar" aria-label="Menu toggle"></DrawerToggle>
      <h2 slot="navbar" className="text-l m-0">
        {currentTitle}
      </h2>

      <ConfirmDialog header='Logged out' cancel opened={!!state.backChannelLogoutHappened}
        onConfirm={loginAgain} onCancel={stayOnPage}>
        <p>You have been logged out. Do you want to log in again?</p>
      </ConfirmDialog>

      <Suspense fallback={<Placeholder />}>
        <Outlet />
      </Suspense>
    </AppLayout>
  );
}

// sso-kit-demo-lit/frontend/views/main-layout.ts
import { logout as _logout } from '@hilla/frontend';
import '@vaadin-component-factory/vcf-nav';
import '@vaadin/app-layout';
import { AppLayout } from '@vaadin/app-layout';
import '@vaadin/app-layout/vaadin-drawer-toggle';
import '@vaadin/avatar';
import '@vaadin/button';
import '@vaadin/confirm-dialog';
import '@vaadin/icon';
import '@vaadin/menu-bar';
import '@vaadin/scroller';
import '@vaadin/tabs';
import '@vaadin/tabs/vaadin-tab';
import '@vaadin/vaadin-lumo-styles/vaadin-iconset';
import { html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { router } from '../index';
import { hasAccess, views } from '../routes';
import { appStore } from '../stores/app-store';
import { Layout } from './view';

interface RouteInfo {
  path: string;
  title: string;
  icon: string;
}

@customElement('main-layout')
export class MainLayout extends Layout {
  render() {
    return html`
      <vaadin-app-layout primary-section="drawer">
        <header slot="drawer">
          <h1 class="text-l m-0">${appStore.applicationName}</h1>
        </header>
        <vaadin-scroller slot="drawer" scroll-direction="vertical">
          <!-- vcf-nav is not yet an official component -->
          <!-- For documentation, visit https://github.com/vaadin/vcf-nav#readme -->
          <vcf-nav aria-label="${appStore.applicationName}">
            ${this.getMenuRoutes().map(
              (viewRoute) => html`
                <vcf-nav-item path=${router.urlForPath(viewRoute.path)}>
                  <span class="${viewRoute.icon} nav-item-icon" slot="prefix" aria-hidden="true"></span>
                  ${viewRoute.title}
                </vcf-nav-item>
              `
            )}
          </vcf-nav>
        </vaadin-scroller>

        <footer slot="drawer">
          ${appStore.user
            ? html`
              <div className="flex items-center gap-m">
                ${appStore.user.fullName}
              </div>
              <vaadin-button @click="${this.logout}">Sign out</vaadin-button>
            `
            : appStore.registeredProviders.map(
              client => html`<a router-ignore href="/oauth2/authorization/${client}">Sign in with ${client}</a>`
            )}
        </footer>

        <vaadin-drawer-toggle slot="navbar" aria-label="Menu toggle"></vaadin-drawer-toggle>
        <h2 slot="navbar" class="text-l m-0">${appStore.currentViewTitle}</h2>

        <vaadin-confirm-dialog
          header="Logged out"
          cancel-button-visible
          @confirm="${this.loginAgain}"
          @cancel="${this.stayOnPage}"
          .opened="${appStore.backChannelLogoutHappened}"
        >
          <p>You have been logged out. Do you want to log in again?</p>
        </vaadin-confirm-dialog>

        <slot></slot>
      </vaadin-app-layout>
    `;
  }

  connectedCallback() {
    super.connectedCallback();
    this.classList.add('block', 'h-full');
    this.reaction(
      () => appStore.location,
      () => {
        AppLayout.dispatchCloseOverlayDrawerEvent();
      }
    );
  }

  private async stayOnPage() {
    await _logout(); // Logout on the server
    appStore.clearUserInfo(); // Logout on the client
  }

  private async loginAgain() {
    await _logout(); // Logout on the server
    location.href = appStore.loginUrl!;
  }

  private async logout() {
    await _logout(); // Logout on the server
    location.href = appStore.logoutUrl!; // Logout on the provider
  }
  
  private getMenuRoutes(): RouteInfo[] {
    return views.filter((route) => route.title).filter(hasAccess) as RouteInfo[];
  }
}
