// sso-kit-react-demo/frontend/views/about/AboutView.tsx
import { AuthContext } from "Frontend/useAuth.js";
import { useContext } from "react";

export default function AboutView() {
  const { state } = useContext(AuthContext);
  return (
    <div className="flex flex-col h-full items-center justify-center p-l text-center box-border">
      <img style={{ width: '200px' }} src="images/empty-plant.png" />
      <h2>This place is about you</h2>
      <p>Username: {state.user!.preferredUsername}</p>
      <p>Full name: {state.user!.fullName}</p>
      <p>Email: {state.user!.email}</p>
      <p>Roles: {state.user!.roles?.join(', ')}</p>
    </div>
  );
}

// sso-kit-demo-lit/frontend/views/about/about-view.ts
import { appStore } from 'Frontend/stores/app-store';
import { html } from 'lit';
import { customElement } from 'lit/decorators.js';
import { View } from '../../views/view';

@customElement('about-view')
export class AboutView extends View {
  render() {
    return html`<div>
      <img style="width: 200px;" src="images/empty-plant.png" />
      <p>Username: ${appStore.user!.preferredUsername}</p>
      <p>Full name: ${appStore.user!.fullName}</p>
      <p>Email: ${appStore.user!.email}</p>
      <p>Roles: ${appStore.user!.roles?.join(', ')}</p>
    </div>`;
  }

  connectedCallback() {
    super.connectedCallback();
    this.classList.add(
      'flex',
      'flex-col',
      'h-full',
      'items-center',
      'justify-center',
      'p-l',
      'text-center',
      'box-border'
    );
  }
}
